# Site settings
title: Sticky Sidebar ðŸ˜Ž
tag_text: Sticky Sidebar ðŸ˜Ž
description: 

# Build settings
markdown: kramdown
exclude: ["README.md", "node_modules"]
sass:
  style: compressed
repository: abouolia/sticky-sidebar.git